spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 774521275942-mla6dhlapk40h47rr56fc2tadcin3br8.apps.googleusercontent.com
            clientSecret: z081TxVKmBFeIInbNSShtHlR
